### ISSUE TITLE
Fixtures are called as tests

### ISSUE THREAD

**Issue by cajopa** [bitprophet/pytest-relaxed#9]
The documentation for pytest-relaxed states that "Objects decorated as fixtures with @pytest.fixture are, of course, also skipped.", however evidence indicates that this is not the case.

```python
import pytest


@pytest.fixture()
def thing():
    print('thing')
    return 4

def blah(thing):
    print('blah')
    print(thing)
```

Running pytest with this results in an error message indicating the fixture being run directly, and the test case `thing` failing:

> Fixture "thing" called directly. Fixtures are not meant to be called directly,
> but are created automatically when test functions request them as parameters.

Renaming `thing` to `_thing` results in it being skipped as a test but being available as a fixture, as intended. I have encountered this issue when using test methods as well.

**Comment by alextremblay** [comment]
I'm encountering the same problem, except i don't have the luxury of renaming my fixture, as it's an override for a default fixture provided by another plugin (`pyrest-recording`)

```pytest

@pytest.fixture(scope="module")
def vcr_config():
    return dict(
        filter_headers=["X-Auth-Token"],
        record_mode="once",
        cassette_library_dir=str(fixtures_dir / "_private/cassettes"),
    )


@pytest.mark.end_to_end
@pytest.mark.vcr(record_mode="new_episodes")
@pytest.mark.default_cassette("LibreNMS.default.yaml")
class LibreNMS:
    def discovery(self):
        ...
```

**Comment by bitprophet** [comment]
This annoys me periodically too. Gonna see if I can just bang out something real quick that specifically avoids fixtures (same, conceptually, as how the plugin tries to skip conftest.py files and setup/teardown methods).

**Comment by bitprophet** [comment]
2.0.1 is on pypi with this fix!
